const agricultureCategories: string[] = [
  "Agribusiness",
  "Agroecology",
  "Agroforestry",
  "Agronomy",
  "Animal Breeding",
  "Apery",
  "Aquaculture",
  "Biodynamic Agriculture",
  "Composting",
  "Crop Production",
  "Farm Management",
  "Floriculture",
  "Forestry",
  "Gardening",
  "Greenhouse Management",
  "Horticulture",
  "Hydroponics",
  "Irrigation",
  "Landscaping",
  "Organic Farming",
  "Pest Management",
  "Plant Breeding",
  "Poultry",
  "Seed Production",
  "Soil Science",
  "Sustainable Agriculture",
  "Urban Agriculture",
  "Vertical Farming",
];
export default agricultureCategories;
